class ZealError(Exception):
    pass


class NPlusOneError(ZealError):
    pass
